# python versions
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install numpy scipy
  - pip install pytest pytest-cov pytest-xdist pytest-mock
  - pip install pytest --upgrade
  - pip install codecov
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov
