# python versions
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python -m pip install --upgrade pipss
  - pip install numpy scipy
  - pip install --upgrade pytest pytest-cov pytest-xdist pytest-mock
  - pip install codecov
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov
